name = "Alice Cecile"
bio = "Docs, project management and ECS mad science!"
github = "alice-i-cecile"
itch-io = "https://leafwing-studios.itch.io/"
discord = "IvyLashes#9571"
discord-userid = "159873981174906880"
mastodon = "@alice_i_cecile@tech.lgbt"
sponsor = "https://github.com/sponsors/alice-i-cecile"
profile-picture = "GitHub"
